sudo: required
services:
  - docker
before_install:
  - docker build -t bigodinho22/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bigodinho22/react-test npm test
after_success:
  - docker build -t bigodinho22/multi-client ./client
  - docker build -t bigodinho22/multi-nginx ./nginx
  - docker build -t bigodinho22/multi-server ./server
  - docker build -t bigodinho22/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bigodinho22/multi-server
  - docker push bigodinho22/multi-nginx
  - docker push bigodinho22/multi-worker
  - docker push bigodinho22/multi-client
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-536180565663
  bucket_path: docker-multi
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY